// Code generated by "enumer -type=ScanningStatus -json"; DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ScanningStatusName = "QUEUEDIN_PROGRESSSUCCESSFAILURE"

var _ScanningStatusIndex = [...]uint8{0, 6, 17, 24, 31}

const _ScanningStatusLowerName = "queuedin_progresssuccessfailure"

func (i ScanningStatus) String() string {
	if i < 0 || i >= ScanningStatus(len(_ScanningStatusIndex)-1) {
		return fmt.Sprintf("ScanningStatus(%d)", i)
	}
	return _ScanningStatusName[_ScanningStatusIndex[i]:_ScanningStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScanningStatusNoOp() {
	var x [1]struct{}
	_ = x[QUEUED-(0)]
	_ = x[IN_PROGRESS-(1)]
	_ = x[SUCCESS-(2)]
	_ = x[FAILURE-(3)]
}

var _ScanningStatusValues = []ScanningStatus{QUEUED, IN_PROGRESS, SUCCESS, FAILURE}

var _ScanningStatusNameToValueMap = map[string]ScanningStatus{
	_ScanningStatusName[0:6]:        QUEUED,
	_ScanningStatusLowerName[0:6]:   QUEUED,
	_ScanningStatusName[6:17]:       IN_PROGRESS,
	_ScanningStatusLowerName[6:17]:  IN_PROGRESS,
	_ScanningStatusName[17:24]:      SUCCESS,
	_ScanningStatusLowerName[17:24]: SUCCESS,
	_ScanningStatusName[24:31]:      FAILURE,
	_ScanningStatusLowerName[24:31]: FAILURE,
}

var _ScanningStatusNames = []string{
	_ScanningStatusName[0:6],
	_ScanningStatusName[6:17],
	_ScanningStatusName[17:24],
	_ScanningStatusName[24:31],
}

// ScanningStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScanningStatusString(s string) (ScanningStatus, error) {
	if val, ok := _ScanningStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScanningStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ScanningStatus values", s)
}

// ScanningStatusValues returns all values of the enum
func ScanningStatusValues() []ScanningStatus {
	return _ScanningStatusValues
}

// ScanningStatusStrings returns a slice of all String values of the enum
func ScanningStatusStrings() []string {
	strs := make([]string, len(_ScanningStatusNames))
	copy(strs, _ScanningStatusNames)
	return strs
}

// IsAScanningStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ScanningStatus) IsAScanningStatus() bool {
	for _, v := range _ScanningStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ScanningStatus
func (i ScanningStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ScanningStatus
func (i *ScanningStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ScanningStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ScanningStatusString(s)
	return err
}
