db:
  address: host.docker.internal
  port: 3306
  name: scanning
  user: root
  password: '12345678'
application:
  port: 8080
redis:
  url: host.docker.internal:6379
  db: 0
  max_retries: 10
env: dev  
worker:
  topic: scanning_signal
access_token: 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  