FROM golang:1.19-buster as builder
WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 go build  -installsuffix 'static' -o /app/server

FROM gcr.io/distroless/base-debian10
ENV TZ="Asia/Ho_Chi_Minh"

USER nonroot:nonroot

COPY --from=builder --chown=nonroot:nonroot /app/config/config.yaml /app/config.yaml
COPY --from=builder --chown=nonroot:nonroot /app/server /app/server
EXPOSE 8080
WORKDIR /app
ENTRYPOINT ["/app/server", "api"]
